# Generated by Django 5.1.15 on 2026-10-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('Garba & Navratri', 'Garba & Navratri Festival'), ('Orchestra', 'Bollywood Orchestra & Live Band'), ('Wedding', 'Wedding Lagangeet & Sangeet'), ('International', 'International Tour / Show'), ('Corporate', 'Corporate Event & Award Show'), ('Other', 'Other Special Occasion')], default='Garba & Navratri', max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New Inquiry'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.CharField(help_text='Path relative to static folder', max_length=255)),
                ('icon', models.CharField(default='fa-solid fa-music', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Performance Categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SingerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brijesh Parekh', max_length=100)),
                ('tagline', models.CharField(default='Playback Singer & Electrifying Stage Performer', max_length=200)),
                ('shows_count', models.IntegerField(default=4000, help_text='Total live shows performed')),
                ('countries_count', models.IntegerField(default=15, help_text='Countries performed in')),
                ('years_experience', models.IntegerField(default=20, help_text='Years of professional singing')),
                ('bio_short', models.TextField(default="Let me introduce to a very talented, electrifying performer and sensational singer. Whether it's a wedding or concert, when he steps on the stage he sets it on fire. Playback singer in many Gujarati albums and movies with over 4000 shows in India and abroad.")),
                ('bio_full', models.TextField(default="Brijesh Parekh is one of Gujarat's most celebrated playback singers and dynamic live performers. With over 4,000 successful shows globally across India, USA, UK, West Indies, and Africa, Brijesh Parekh creates magic on stage with high-energy Garba, soulful Lagangeet (wedding songs), nostalgic Bollywood Orchestra, and thrilling DJ nights. Known for his captivating voice, incredible vocal range, and unmatched stage command, he brings life and grandeur to every celebration.")),
                ('phone_primary', models.CharField(default='+91 9574805348', max_length=30)),
                ('phone_secondary', models.CharField(default='+91 9825000000', max_length=30)),
                ('email', models.EmailField(default='brijeshparekh@gmail.com', max_length=254)),
                ('address', models.CharField(default='Ahmedabad, Gujarat, India', max_length=255)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/brijeshparekhnight?mibextid=LQQJ4d')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/thebrijeshparekh?igsh=amIwamgxbjU0aDFh&utm_source=qr')),
                ('youtube_url', models.URLField(default='https://youtube.com/@brijeshparekhofficial5953?si=E4l35MJxYiL2Pbgt')),
                ('google_maps_url', models.URLField(default='https://maps.app.goo.gl/x4TiHEh2ehnbZqW7A?g_st=com.google.maps.preview.copy')),
                ('hero_video_path', models.CharField(default='V1.MP4', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('role_or_event', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('avatar', models.CharField(default='images/artist-1.jpg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_path', models.CharField(help_text='Path relative to static folder e.g. Garba/1.jpg', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='singer_app.performancecategory')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(default='04:30', max_length=20)),
                ('audio_url', models.CharField(default='https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', help_text='URL or static path to audio sample', max_length=255)),
                ('cover_image', models.CharField(default='pics/solo3.jpg', max_length=255)),
                ('is_popular', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='singer_app.performancecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city_country', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(default='08:00 PM Onwards', max_length=100)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Past', 'Past'), ('Sold Out', 'Sold Out')], default='Upcoming', max_length=20)),
                ('booking_link', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='singer_app.performancecategory')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
