# Generated by Django 5.2.17 on 2026-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singerprofile',
            name='email',
            field=models.EmailField(default='brijesh71090parekh@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='singerprofile',
            name='phone_primary',
            field=models.CharField(default='+91 95748 05348', max_length=30),
        ),
        migrations.AlterField(
            model_name='singerprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
