# Generated by Django 5.2.17 on 2026-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_app', '0002_alter_singerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_type',
            field=models.CharField(choices=[('Garba, Navratri & Marriage', 'Garba, Navratri & Marriage'), ('Bollywood Live', 'Bollywood Live Concert'), ('Vaidik Lagangeet', 'Vaidik Lagangeet & Sangeet'), ('Spiritual Music (Bhajan)', 'Spiritual Music (Bhajan)'), ('Corporate / Gala Event', 'Corporate / Gala Event'), ('Other Special Occasion', 'Other Special Occasion')], default='Garba, Navratri & Marriage', max_length=50),
        ),
    ]
