# Generated by Django 5.2.17 on 2026-10-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_app', '0003_alter_bookinginquiry_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_type',
            field=models.CharField(choices=[('Garba', 'Garba'), ('Bollywood Live', 'Bollywood Live Concert'), ('Wedding Songs', 'Wedding Songs & Sangeet'), ('Spiritual Music (Bhajan)', 'Spiritual Music (Bhajan)'), ('Corporate / Gala Event', 'Corporate / Gala Event'), ('Other Special Occasion', 'Other Special Occasion')], default='Garba', max_length=50),
        ),
    ]
