# Generated by Django 5.2.17 on 2026-10-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer_app', '0004_alter_bookinginquiry_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiotrack',
            options={'verbose_name': 'Audio Track', 'verbose_name_plural': 'Audio Tracks'},
        ),
        migrations.AlterModelOptions(
            name='bookinginquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking Inquiry', 'verbose_name_plural': 'Booking Inquiries (Contact Form Submissions)'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Media (Photos & Videos)'},
        ),
        migrations.AlterModelOptions(
            name='performancecategory',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Performance Category', 'verbose_name_plural': 'Performance Categories'},
        ),
        migrations.AlterModelOptions(
            name='showevent',
            options={'ordering': ['event_date'], 'verbose_name': 'Show Event', 'verbose_name_plural': 'Shows & Events'},
        ),
        migrations.AlterModelOptions(
            name='singerprofile',
            options={'verbose_name': 'Singer Profile', 'verbose_name_plural': 'Singer Profile'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials & Reviews'},
        ),
    ]
